<a href="https://colab.research.google.com/github/YeonJungHoon/NLP-/blob/main/12th_Step(Glove).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1]

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1
print("단어 집합의 개수: {}".format(vocab_size))


단어 집합의 개수: 16


In [2]:
X_encoded = tokenizer.texts_to_sequences(sentences)
print("정수 인코딩 결과: {}".format(X_encoded))

max_len = max(len(word) for word in X_encoded)
print("최대 길이: {}".format(max_len))

정수 인코딩 결과: [[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]
최대 길이: 4


In [32]:
X_train = pad_sequences(X_encoded, padding = 'post' , maxlen = max_len)
y_train = np.array(y_train)

print("패딩 시퀀스 결과: \n{}".format(X_train))

패딩 시퀀스 결과: 
[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

embedding_dim  = 4

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length = max_len))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(X_train, y_train, epochs = 100, verbose = 2)

#Pre-trained-Embedding(Glove)

In [28]:
embedding_dict = dict()

f = open('glove.6B.100d.txt', encoding= 'UTF-8')

for line in f:
  word_vector = line.split()
  word = word_vector[0]
  
  word_vector_arr = np.asarray(word_vector[1:], dtype = 'float32')
  embedding_dict[word] = word_vector_arr
  
f.close()

print('%s 개의 word_vector가 있습니다.' % len(embedding_dict))



166722 개의 word_vector가 있습니다.


In [29]:
embedding_matrix = np.zeros((vocab_size, 100))
print("임베딩 행렬의 크기: {}".format(np.shape(embedding_matrix)))
print('벡터의 차원 수 :',len(embedding_dict['respectable']))

임베딩 행렬의 크기: (16, 100)
벡터의 차원 수 : 100


In [20]:
from pprint import pprint
pprint(tokenizer.word_index.items())

dict_items([('nice', 1), ('great', 2), ('best', 3), ('amazing', 4), ('stop', 5), ('lies', 6), ('pitiful', 7), ('nerd', 8), ('excellent', 9), ('work', 10), ('supreme', 11), ('quality', 12), ('bad', 13), ('highly', 14), ('respectable', 15)])


In [21]:
for word, index in tokenizer.word_index.items():
  
  vector_value = embedding_dict.get(word)
  if vector_value is not None:
    embedding_matrix[index] = vector_value

  

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

output_dim = 100

model = Sequential()
e = Embedding(vocab_size, output_dim, weights = [embedding_matrix], input_length = max_len, trainable = False)
model.add(e) 
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid')) # input_shape = 2D Tensor(batch_size, input_dim) --> output_shape = 2D Tensor(batch_size, units)
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 
model.fit(X_train, y_train, epochs = 100, verbose = 2)



Epoch 1/100
1/1 - 1s - loss: 0.6931 - accuracy: 0.4286 - 563ms/epoch - 563ms/step
Epoch 2/100
1/1 - 0s - loss: 0.6931 - accuracy: 0.5714 - 4ms/epoch - 4ms/step
Epoch 3/100
1/1 - 0s - loss: 0.6930 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.6929 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 5/100
1/1 - 0s - loss: 0.6929 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 6/100
1/1 - 0s - loss: 0.6928 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.6927 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 8/100
1/1 - 0s - loss: 0.6927 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 9/100
1/1 - 0s - loss: 0.6926 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 10/100
1/1 - 0s - loss: 0.6925 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.6924 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 12/100
1/1 - 0s - loss: 0.6924 - accuracy: 0.5714 - 3ms/epoch - 3ms/step
Epoch 13/100
1/1 - 0s - loss: 0.6923 - accuracy: 0.5714 -