<a href="https://colab.research.google.com/github/YeonJungHoon/NLP-/blob/main/9th_Step(RNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.models import Sequential
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape = (8,2,20), return_sequences = True))
model.summary()


Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_7 (SimpleRNN)    (8, 2, 3)                 72        
                                                                 
Total params: 72
Trainable params: 72
Non-trainable params: 0
_________________________________________________________________


In [8]:
import numpy as np

timesteps = 10
input_dim = 4
hidden_units = 8

inputs = np.random.random((timesteps, input_dim))

hidden_state_t = np.zeros((hidden_units,))

print('초기 은닉 상태: {}'.format(hidden_state_t))

초기 은닉 상태: [0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
Wx = np.random.random((hidden_units, input_dim))
Wh = np.random.random((hidden_units, hidden_units))
b = np.random.random((hidden_units,))

print('가중치 Wx의 크기: {}'.format(Wx.shape))
print('가중치 Wh의 크기: {}'.format(Wh.shape))
print('평향 값의 크기: {}'.format(b.shape))

가중치 Wx의 크기: (8, 4)
가중치 Wh의 크기: (8, 8)
평향 값의 크기: (8,)


In [14]:
total_hidden_states = []

for input_t in inputs:
  output_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh, hidden_state_t) + b)
  
  total_hidden_states.append(list(output_t))
  hidden_state_t = output_t
  
total_hidden_states = np.stack(total_hidden_states, axis = 0)

print("모든 은닉 시점의 상태: \n{}".format(total_hidden_states))

모든 은닉 시점의 상태: 
[[0.9999905  0.99986443 0.99996008 0.99984176 0.99947672 0.99994474
  0.99999776 0.99986095]
 [0.9999957  0.99989805 0.99999432 0.99997845 0.99984931 0.9999584
  0.99999963 0.99993056]
 [0.99999246 0.9998693  0.99998017 0.99992342 0.99968665 0.99994734
  0.99999868 0.99989485]
 [0.99999609 0.99989767 0.99999545 0.99998356 0.99984836 0.99995233
  0.99999965 0.99994146]
 [0.99999324 0.9999195  0.99999259 0.99994819 0.99980872 0.99995695
  0.99999942 0.99987689]
 [0.99999434 0.99989527 0.99999442 0.99997271 0.99989145 0.99996032
  0.99999953 0.99991528]
 [0.99998642 0.99988261 0.99995734 0.99972801 0.9994645  0.99994169
  0.99999688 0.99979693]
 [0.99999577 0.99990895 0.99999715 0.99998594 0.99993817 0.99996994
  0.99999979 0.99992766]
 [0.99999444 0.99987622 0.9999889  0.99996146 0.99982122 0.99995969
  0.99999935 0.99991556]
 [0.999996   0.99990591 0.99999695 0.99998649 0.99991416 0.9999622
  0.99999975 0.99993674]]


#양방향 순환 신경망

In [ ]:
from tensorflow.keras.layers import Bidirectioanal

timesteps = 10
input_dim = 5

model = Sequential()
#model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True), input_shape=(timesteps, input_dim)))

#LSTM

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [17]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype = np.float32)
print(train_X.shape)

(1, 4, 5)


In [22]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_X)
print('hidden_state: \n{}, shape: {}'.format(hidden_state, hidden_state.shape))


hidden_state: 
[[[ 0.9731527  -0.23259851  0.9003294 ]
  [ 0.612234   -0.9742988   0.37253386]
  [ 0.03955299 -0.9906791  -0.6658047 ]
  [ 0.2162293  -0.9814135   0.86419964]]], shape: (1, 4, 3)


In [21]:
rnn = SimpleRNN(3, return_sequences = True, return_state = True)
hidden_states, last_state = rnn(train_X)

print('hidden_state: \n{}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last_state: {}, shape: {}'.format(last_state, last_state.shape))

hidden_state: 
[[[ 0.99990755 -0.91012466  0.98509073]
  [ 0.98333395  0.38933766  0.99321383]
  [ 0.9545231  -0.9378206   0.7804031 ]
  [ 0.65550745  0.47128794  0.9567648 ]]], shape: (1, 4, 3)
last_state: [[0.65550745 0.47128794 0.9567648 ]], shape: (1, 3)


#LSTM

In [23]:
lstm = LSTM(3, return_sequences = False, return_state = True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))




hidden state : [[-0.25434133 -0.44728935  0.18457057]], shape: (1, 3)
last hidden state : [[-0.25434133 -0.44728935  0.18457057]], shape: (1, 3)
last cell state : [[-0.77042234 -0.81168586  0.5911325 ]], shape: (1, 3)


In [24]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[[-2.6870275e-01  5.7596981e-04 -5.1562572e-01]
  [-3.7434039e-01  1.3531194e-02 -5.5515325e-01]
  [-4.6170062e-01 -7.8548174e-03 -5.2133512e-01]
  [-3.9652446e-01 -1.0455639e-01 -5.8645195e-01]]], shape: (1, 4, 3)
last hidden state : [[-0.39652446 -0.10455639 -0.58645195]], shape: (1, 3)
last cell state : [[-0.93102014 -0.20873393 -2.0938463 ]], shape: (1, 3)


#Bidirectional(LSTM)

In [25]:
k_init = tf.keras.initializers.Constant(value = 0.1)
b_init = tf.keras.initializers.Constant(value = 0)
r_init = tf.keras.initializers.Constant(value = 0.1)



In [28]:
bilstm = Bidirectional(LSTM(3, return_sequences = False, return_state = True, kernel_initializer= k_init, bias_initializer = b_init, recurrent_initializer= r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape: (1, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)
