<a href="https://colab.research.google.com/github/YeonJungHoon/NLP-/blob/main/FifthStep(Padding).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from pprint import pprint
preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
pprint(encoded)

max_len = max(len(item)for item in encoded)
print("최대 길이 {}".format(max_len))

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]
최대 길이 7


In [4]:
for sentence in encoded:
  while len(sentence) < max_len:
    sentence.append(0)
    
padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

#Padding With Keras

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
padded = pad_sequences(encoded)
pprint(padded)
"""
Numpy로 패딩을 진행하였을 때와는 패딩 결과가 다른데 
그 이유는 pad_sequences는 기본적으로 문서의 뒤에 0을 채우는 것이 아니라 
앞에 0으로 채우기 때문입니다. 
뒤에 0을 채우고 싶다면 인자로 padding='post'를 주면됩니다.
"""
pad = pad_sequences(encoded, padding = 'post')
pprint(pad)
pad_test = pad_sequences(encoded, padding = 'post', maxlen = 3)
pprint(pad_test)

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)
array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)
array([[ 1,  5,  0],
       [ 1,  8,  5],
       [ 1,  3,  5],
       [ 9,  2,  0],
       [ 4,  3,  2],
       [ 3,  2,  0],
       [ 1,  4,  6],
       [ 1,

#One-Hot-Encoding

In [11]:
!pip install konlpy

     |████████████████████████████████| 19.4 MB 7.6 MB/s 
     |████████████████████████████████| 448 kB 47.8 MB/s 


In [12]:
from konlpy.tag import Okt
okt = Okt()
tokens = okt.morphs("나는 자연어 처리를 배운다")
pprint(tokens)

['나', '는', '자연어', '처리', '를', '배운다']


In [13]:
word_to_idx = {word:index for index, word in enumerate(tokens)}
print("단어 집합: {}".format(word_to_idx))

단어 집합: {'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [16]:
def one_hot_encoding(word, word_to_idx):
  one_hot_vector = [0] * (len(word_to_idx))
  index = word_to_idx[word]
  one_hot_vector[index] = 1
  return one_hot_vector

one_hot_encoding('자연어', word_to_idx)

[0, 0, 1, 0, 0, 0]

#One-Hot-Encoding With Keras

In [17]:
text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer= Tokenizer()
tokenizer.fit_on_texts([text])
pprint("단어 집합: {}".format(tokenizer.word_index))

"단어 집합: {'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}"


In [20]:
sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
pprint(encoded)

one_hot = to_categorical(encoded)
pprint("one-hot-encoding: {}".format(one_hot))

[2, 5, 1, 6, 3, 7]
('one-hot-encoding: [[0. 0. 1. 0. 0. 0. 0. 0.]\n'
 ' [0. 0. 0. 0. 0. 1. 0. 0.]\n'
 ' [0. 1. 0. 0. 0. 0. 0. 0.]\n'
 ' [0. 0. 0. 0. 0. 0. 1. 0.]\n'
 ' [0. 0. 0. 1. 0. 0. 0. 0.]\n'
 ' [0. 0. 0. 0. 0. 0. 0. 1.]]')
