<a href="https://colab.research.google.com/github/YeonJungHoon/NLP-/blob/main/SixthStep(Split_Data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']
df = pd.DataFrame(values, columns = columns)

X = df['메일 본문']
Y = df['스팸 메일 유무']

print('X 데이터: {}'.format(X.to_list()))
print('Y 데이터: {}'.format(Y.to_list()))


X 데이터: ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
Y 데이터: [1, 0, 0, 1]


In [15]:
np_array = np.arange(0,16).reshape(4,4)
print("전체 데이터:\n {}".format(np_array))
X = np_array[:,:3]
Y = np_array[:,3]
print('X데이터:\n {}'.format(X))
print('Y데이터:\n {}'.format(Y))

전체 데이터:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
X데이터:
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
Y데이터:
 [ 3  7 11 15]


#Sklearn Train, Test Data Split

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 1234)
print(X_train)

[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [22]:
X,y = np.arange(0,24).reshape((12,2)), range(12)
print("X 데이터:\n {}".format(X))
print("Y 데이터:\n {}".format(list(y)))

X 데이터:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Y 데이터:
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [24]:
num_of_train = int(len(X) * 0.8)
num_of_test = int(len(X) -num_of_train)

print("훈련 데이터의 크기: {}".format(num_of_train))
print("테스트 데이터의 크기: {}".format(num_of_test))

X_test = X[num_of_train:]
y_test = y[num_of_train:]
X_train = X[:num_of_train]
y_train = y[:num_of_train]

print(X_test)


훈련 데이터의 크기: 9
테스트 데이터의 크기: 3
[[18 19]
 [20 21]
 [22 23]]


#한국어 데이터 전처리 패키지

In [26]:
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-3ap_m7lv
  Running command git clone -q https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-3ap_m7lv
     |████████████████████████████████| 460.3 MB 4.1 kB/s 
     |████████████████████████████████| 1.2 MB 31.7 MB/s 
     |████████████████████████████████| 462 kB 29.7 MB/s 
     |████████████████████████████████| 132 kB 11.3 MB/s 
     |████████████████████████████████| 4.0 MB 16.3 MB/s 
  Created wheel for pykospacing: filename=pykospacing-0.5-py3-none-any.whl size=2268580 sha256=8a3660ee17265e20e29564124d6336af462315bc0ae0d1affe997be76e602f5e
  Stored in directory: /tmp/pip-ephem-wheel-cache-a50k9gik/wheels/9b/93/81/a2a7dc8c66ede5bf30634d20635f32b95eac7ca2ea8844058b
  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=68712 sha256=31468ad24d63a36f13130667b61e8456f59574e29791fc1983c8a0a014ba8dbf
  Stored in directory: /root/.cache/pip/wheels/62/76/4c/aa25851149f3f6d

In [27]:
sent = '김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.'
new_sent = sent.replace(" ", "")
print(new_sent)

김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다.


In [28]:
from pykospacing import Spacing
spacing = Spacing()
konspacing_sent = spacing(new_sent)

print(sent)
print(konspacing_sent)

김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.


In [29]:
!pip install git+https://github.com/ssut/py-hanspell.git


  Cloning https://github.com/ssut/py-hanspell.git to /tmp/pip-req-build-l16b4hun
  Running command git clone -q https://github.com/ssut/py-hanspell.git /tmp/pip-req-build-l16b4hun
  Created wheel for py-hanspell: filename=py_hanspell-1.1-py3-none-any.whl size=4868 sha256=c652f97dbbdbd6bc3329fd528f7bb6d9bafd727f3529093fdf7db7af8282f865
  Stored in directory: /tmp/pip-ephem-wheel-cache-mc5dm04m/wheels/ab/f5/7b/d4124bb329c905301baed80e2ae45aa14e824f62ebc3ec2cc4
Successfully built py-hanspell


In [30]:
from hanspell import spell_checker

sent = "맞춤법 틀리면 외 않되? 쓰고싶은대로쓰면돼지 "
spelled_sent = spell_checker.check(sent)
hanspell_sent =  spelled_sent.checked
print(hanspell_sent)

맞춤법 틀리면 왜 안돼? 쓰고 싶은 대로 쓰면 되지
